#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ release TYPE
Release a new version

Parameters:
  \$1: one of major, minor, patch

Example:
  $ release patch
EOF
  exit
fi

command -v npm >/dev/null || { echo "npm is not installed" 1>&2; exit 127; }
command -v oclif >/dev/null || { echo "oclif is not installed" 1>&2; exit 127; }

if [ "$1" != "major" ] && [ "$1" != "minor" ] && [ "$1" != "patch" ]; then
  echo "\$1 has to be one of: major, minor, patch"
  exit 1
fi

VERSION="$(npm --no-git-tag-version version $1)"

# track changes to release relevant files only here
git update-index --no-assume-unchanged npm-shrinkwrap.json
npm shrinkwrap

echo "Releasing '$VERSION'"
git add npm-shrinkwrap.json package.json
git commit -m $VERSION
git tag $VERSION

# ignore for development
git update-index --assume-unchanged npm-shrinkwrap.json
